theme: jekyll-theme-architect
title: [MMPERF - single core matmul performance benchmark]
description: [Single Core MatMul performance benchmark]

github:
  owner_url: https://github.com/mmperf/mmperf
